name: cityvet_app
description: "A capstone project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  dotted_border: ^3.1.0
  dropdown_search: ^6.0.2
  firebase_core: ^3.15.1
  firebase_core_web: ^2.24.1
  firebase_messaging: ^15.2.9
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.8.0
  gal: ^2.3.2
  geocoding: ^3.0.0
  geolocator: ^10.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  mobile_scanner: ^7.0.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/cityvet-logo.png
    - assets/images/forgot_pass.png
    - assets/images/reset_pass.png
    - assets/images/default_avatar.png
    - assets/images/sample_dog.png
    - assets/images/qr_code.png
    - assets/images/cat.png
    - assets/images/dog.png
    - assets/images/cattle.png
    - assets/images/goat.png
    - assets/images/chicken.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600

