// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMsafTzaxUuzkxHWDhWnP3ZYAjl4KjVgk',
    appId: '1:431838970874:web:af369c7d41f8e076411a43',
    messagingSenderId: '431838970874',
    projectId: 'cityvet-d65f7',
    authDomain: 'cityvet-d65f7.firebaseapp.com',
    storageBucket: 'cityvet-d65f7.firebasestorage.app',
    measurementId: 'G-47BVRJXXGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG2lK6qavvTgCY2Ma0LtmKOt-YZ0R2poI',
    appId: '1:431838970874:android:d00cb3db73c81804411a43',
    messagingSenderId: '431838970874',
    projectId: 'cityvet-d65f7',
    storageBucket: 'cityvet-d65f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8l6Fgge010V_nqkcd9Ub061i8nASaRSg',
    appId: '1:431838970874:ios:6b256264be99ccdf411a43',
    messagingSenderId: '431838970874',
    projectId: 'cityvet-d65f7',
    storageBucket: 'cityvet-d65f7.firebasestorage.app',
    iosBundleId: 'com.example.cityvetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8l6Fgge010V_nqkcd9Ub061i8nASaRSg',
    appId: '1:431838970874:ios:6b256264be99ccdf411a43',
    messagingSenderId: '431838970874',
    projectId: 'cityvet-d65f7',
    storageBucket: 'cityvet-d65f7.firebasestorage.app',
    iosBundleId: 'com.example.cityvetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMsafTzaxUuzkxHWDhWnP3ZYAjl4KjVgk',
    appId: '1:431838970874:web:e204a4ec244650e4411a43',
    messagingSenderId: '431838970874',
    projectId: 'cityvet-d65f7',
    authDomain: 'cityvet-d65f7.firebaseapp.com',
    storageBucket: 'cityvet-d65f7.firebasestorage.app',
    measurementId: 'G-7CXH5XE4T3',
  );
}
